### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kimaiy0** [henriqueclaranhan/telegram-music-downloader-bot#19]
ils.DownloadError: ERROR: Sign in to confirm you’re not
a bot

**Comment by kimaiy0** [comment]
guess ip has  been blocked by youtube....there is nothing wrong for now 👍

**Comment by kimaiy0** [comment]
thanks

**Comment by henriqueclaranhan** [comment]
it really appears that YouTube is now blocking downloads, updating the youtube-dl version may mitigate the problem
