### ISSUE TITLE
Download Error showing bro.. { DownloadError(message, exc_info) 2021-05-08T02:29:00.449553+00:00 app[worker.1]: youtube_dl.utils.DownloadError: ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one. }  

### ISSUE THREAD

**Issue by Hillard-har** [henriqueclaranhan/telegram-music-downloader-bot#3]

**Comment by exodojaffar** [comment]
# Good Morning.

Right away, I give the tip to search the error on Google, and if you have not found any solution, open an issue.

## About the issue
 I ask for more information about the error, and where you are having it, whether it is on your machine or on a server.

## First comments
If it is on your machine, it is necessary to install the libraries listed in the file "requirements.txt".

If it is on a server, see the documentation for the service you are using.

## About the libs
Some libraries use executables that are already on your computer, so to use the library you need to install some of these executables.

**Comment by Hillard-har** [comment]
Sorry bro I forgot to say, I fixed the issue

**Comment by mrflyman** [comment]
How did you solve the problem
