### ISSUE TITLE
[ffmpeg] Post-process file exists, skipping                                           

### ISSUE THREAD

**Issue by cool4tec** [henriqueclaranhan/telegram-music-downloader-bot#8]
hello i try to use telegram music bot the problem when i search and download is not download i see this
[ffmpeg] Post-process file ./teest1.mp3 exists, skipping                                           
i thing i need to update bot.py
so what i need to do to fix this problem?

**Comment by frencymontana** [comment]
did you ever fix this?

**Comment by henriqueclaranhan** [comment]
The problem described never occurred to me.
